name: user_repository
description: "The repo that handles user"
publish_to:
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  supabase: ^2.2.2
  rxdart: ^0.27.7
  supabase_flutter: ^2.5.6

flutter:
  uses-material-design: true
